-- Label
INSERT INTO Label (label_name)
VALUES ('Design'),
       ('Debugging'),
       ('Creativity'),
       ('Refactoring'),
       ('Management'),
       ('Coding');

-- Project
INSERT INTO Project (project_name, project_status, start_date, end_date, description, current_sprint_id)
VALUES ('Software Development', 'IN_PROGRESS', '2023-01-01', NULL,
        'A project for developing software applications.', NULL),
       ('Marketing Campaign', 'IN_PROGRESS', '2023-02-01', NULL,
        'A marketing campaign to promote our products.', NULL),
       ('Customer Support Improvement', 'FUTURE', NULL, NULL,
        'A project to enhance customer support services.', NULL),
       ('Product Launch', 'CLOSED', '2021-04-01', '2022-07-31',
        'A project for launching a new product into the market.', NULL);

-- Employee
INSERT INTO Employee (name, surname, username, password, role, email)
VALUES ('Alice', 'Smith', 'LunaStar', 'q2gfh', 'REGULAR', 'LunaStar@example.com'),
       ('Benjamin', 'Johnson', 'NeonBolt', 'm8k3a', 'EMPOWERED', 'NeonBolt@example.com'),
       ('Charlotte', 'Williams', 'CyberJinx', 't7zqb', 'REGULAR', 'CyberJinx@example.com'),
       ('David', 'Jones', 'QuantumFox', 'p1xra', 'EMPOWERED', 'QuantumFox@example.com'),
       ('Emily', 'Brown', 'PixelRider', 'a5bhm', 'REGULAR', 'PixelRider@example.com'),
       ('Felix', 'Davis', 'MysticWisp', 'w9dck', 'EMPOWERED', 'MysticWisp@example.com'),
       ('Grace', 'Miller', 'NovaFury', 'k6lny', 'REGULAR', 'NovaFury@example.com'),
       ('Henry', 'Wilson', 'VortexPulse', 's4vjp', 'REGULAR', 'VortexPulse@example.com'),
       ('Isabella', 'Moore', 'BlazeSpecter', 'y3fdu', 'REGULAR', 'BlazeSpecter@example.com'),
       ('Jack', 'Taylor', 'EchoRanger', 'y3fdu', 'REGULAR', 'EchoRanger@example.com'),
       ('Katherine', 'Anderson', 'SwiftShadow', 'x9err', 'EMPOWERED', 'SwiftShadow@example.com'),
       ('Liam', 'Thomas', 'SolarFlare', 'c2tyu', 'REGULAR', 'SolarFlare@example.com'),
       ('Mia', 'Jackson', 'ZenithRider', 'v6inr', 'EMPOWERED', 'ZenithRider@example.com'),
       ('Nathan', 'White', 'NexusGlider', 'b4ahk', 'REGULAR', 'NexusGlider@example.com'),
       ('Olivia', 'Harris', 'StormHaven', 'r5kfi', 'REGULAR', 'StormHaven@example.com'),
       ('Peter', 'Martin', 'FrostByte', 'z8lco', 'REGULAR', 'FrostByte@example.com'),
       ('Quinn', 'Thompson', 'AeroViper', 'o1qsw', 'EMPOWERED', 'AeroViper@example.com'),
       ('Rachel', 'Garcia', 'NeonWave', 'o1qsw', 'REGULAR', 'NeonWave@example.com'),
       ('Samuel', 'Martinez', 'QuantumSpark', 'n3mae', 'EMPOWERED', 'QuantumSpark@example.com'),
       ('Taylor', 'Robinson', 'EmberPilot', 'i9puy', 'REGULAR', 'EmberPilot@example.com'),
       ('Ulysses', 'Clark', 'SapphireSwift', 'f4eoi', 'EMPOWERED', 'SapphireSwift@example.com'),
       ('Victoria', 'Rodriguez', 'ThunderVolt', 'l6jrt', 'REGULAR', 'ThunderVolt@example.com'),
       ('William', 'Lewis', 'LunarNova', 'd2cxl', 'EMPOWERED', 'LunarNova@example.com'),
       ('Xander', 'Lee', 'StarStriker', 'g8tbi', 'REGULAR', 'StarStriker@example.com'),
       ('Yasmine', 'Walker', 'FireFlicker', 'j5svw', 'EMPOWERED', 'FireFlicker@example.com'),
       ('Zachary', 'Hall', 'EchoBreeze', 'e1uzr', 'REGULAR', 'EchoBreeze@example.com'),
       ('Ava', 'Hall', 'PlasmaWave', 'q9mpj', 'REGULAR', 'PlasmaWave@example.com'),
       ('Brian', 'Allen', 'QuantumQuasar', 'a3rff', 'REGULAR', 'QuantumQuasar@example.com'),
       ('Cassandra', 'Young', 'NeonNebula', 'w7yxe', 'REGULAR', 'NeonNebula@example.com'),
       ('Daniel', 'Hernandez', 'BlazeBolt', 'k4lnu', 'EMPOWERED', 'BlazeBolt@example.com'),
       ('Ella', 'King', 'SolarSpectra', 's6vjk', 'REGULAR', 'SolarSpectra@example.com'),
       ('Franklin', 'Wright', 'MysticMarauder', 'p2xrm', 'EMPOWERED', 'MysticMarauder@example.com'),
       ('Gabriella', 'Scott', 'VortexVagrant', 'm9k3z', 'REGULAR', 'bVortexVagrant@example.com'),
       ('Hayden', 'Cooper', 'CyberCipher', 't4zqr', 'REGULAR', 'CyberCipher@example.com'),
       ('Ivy', 'Green', 'PixelPhantom', 'y7fdd', 'REGULAR', 'PixelPhantom@example.com'),
       ('Jasper', 'Adams', 'NovaNemesis', 'u1pou', 'EMPOWERED', 'NovaNemesis@example.com'),
       ('Kaitlyn', 'Baker', 'SwiftSpectacle', 'x6erl', 'REGULAR', 'SwiftSpectacle@example.com'),
       ('Leo', 'Nelson', 'ZenithZephyr', 'c9tyi', 'EMPOWERED', 'ZenithZephyr@example.com'),
       ('Lily', 'Carter', 'FrostFury', 'v2inm', 'REGULAR', 'FrostFury@example.com'),
       ('Mason', 'Mitchell', 'AeroAbyss', 'b6ahc', 'EMPOWERED', 'AeroAbyss@example.com'),
       ('Nora', 'Perez', 'NexusNebula', 'r3kfi', 'REGULAR', 'NexusNebula@example.com'),
       ('Owen', 'Roberts', 'StormStrider', 'z5lcy', 'EMPOWERED', 'StormStrider@example.com'),
       ('Penelope', 'Turner', 'EmberEclipse', 'o8qsa', 'REGULAR', 'EmberEclipse@example.com'),
       ('Quentin', 'Phillips', 'SapphireShade', 'h1wxx', 'EMPOWERED', 'SapphireShade@example.com'),
       ('Ruby', 'Campbell', 'ThunderTwist', 'n7maa', 'REGULAR', 'ThunderTwist@example.com'),
       ('Simon', 'Parker', 'LunarLoom', 'i4pue', 'REGULAR', 'LunarLoom@example.com'),
       ('Sophia', 'Evans', 'StarStitch', 'f9eou', 'REGULAR', 'StarStitch@example.com'),
       ('Theo', 'Edwards', 'FireFlame', 'l2jrt', 'REGULAR', 'FireFlame@example.com'),
       ('Ursula', 'Collins', 'EchoEssence', 'd6cxl', 'EMPOWERED', 'EchoEssence@example.com'),
       ('Vincent', 'Stewart', 'PlasmaPulse', 'g2tbk', 'REGULAR', 'PlasmaPulse@example.com'),
       ('Abigail', 'Sanchez', 'QuantumQuiver', 'j8svi', 'EMPOWERED', 'QuantumQuiver@example.com'),
       ('Benjamin', 'Morris', 'NeonNinja', 'e5uzw', 'REGULAR', 'NeonNinja@example.com'),
       ('Caleb', 'Rogers', 'BlazeBlitz', 'q1mpo', 'REGULAR', 'BlazeBlitz@example.com'),
       ('Delilah', 'Reed', 'SolarSurge', 'a8rfd', 'REGULAR', 'SolarSurge@example.com'),
       ('Elijah', 'Cook', 'MysticMingle', 'w3yxa', 'EMPOWERED', 'MysticMingle@example.com'),
       ('Oleg', 'Morgan', 'VortexVirtuoso', 'k7lns', 'REGULAR', 'VortexVirtuoso@example.com'),
       ('Dmitrii', 'Bell', 'CyberCraze', 's5vjp', 'EMPOWERED', 'CyberCraze@example.com');

-- Sprint
INSERT INTO Sprint (start_date, end_date, sprint_status, goal, project_id, ordinal_number_in_project)
VALUES (NULL, NULL, 'FUTURE', 'Implement Customer Feedback Feature',
        SELECT id FROM Project WHERE project_name = 'Customer Support Improvement', 1),
       ('2023-02-01', '2023-04-15', 'CLOSED', 'Bug Fixes and Performance Optimization',
       SELECT id FROM Project WHERE project_name = 'Marketing Campaign', 1),
       (NULL, NULL, 'FUTURE', 'Prepare Marketing Campaign for Product Launch',
       SELECT id FROM Project WHERE project_name = 'Customer Support Improvement', 2),
       ('2023-01-01', '2023-02-15', 'CLOSED', 'Enhance User Interface and User Experience',
       SELECT id FROM Project WHERE project_name = 'Software Development', 1),
       ('2023-04-15', NULL, 'IN_PROGRESS', 'Implement Security Updates and Bug Fixes',
       SELECT id FROM Project WHERE project_name = 'Marketing Campaign', 2),
       ('2023-02-15', '2023-05-28', 'CLOSED', 'Develop New Features for Product Enhancement',
       SELECT id FROM Project WHERE project_name = 'Software Development', 2),
       ('2023-05-28', NULL, 'IN_PROGRESS', 'Implement Performance Improvements',
       SELECT id FROM Project WHERE project_name = 'Software Development', 3),
       (NULL, NULL, 'FUTURE', 'Enhance Database Schema and Optimization',
       SELECT id FROM Project WHERE project_name = 'Customer Support Improvement', 3),
       (NULL, NULL, 'FUTURE', 'Develop Integration with Third-Party Services',
       SELECT id FROM Project WHERE project_name = 'Software Development', 4);

-- Update project
UPDATE Project SET current_sprint_id = (SELECT id FROM Sprint WHERE goal = 'Implement Performance Improvements')
               WHERE id = (SELECT id FROM Project WHERE project_name = 'Software Development');
UPDATE Project SET current_sprint_id = (SELECT id FROM Sprint WHERE goal = 'Implement Security Updates and Bug Fixes')
               WHERE id = (SELECT id FROM Project WHERE project_name = 'Marketing Campaign');


-- Task

INSERT INTO Task (task_name, task_points, task_status, task_priority, creation_date, last_update_date, due_date,
                  employee_id, sprint_id, description)
VALUES ('Development of Payment Gateway Integration', 1, 'TO_DO', 'HIGH', '2023-01-01T10:00:00', '2023-01-01T10:00:00',
        NULL, SELECT id FROM Employee WHERE name = 'David', SELECT id FROM Sprint WHERE goal = 'Implement Customer Feedback Feature',
        'Develop user authentication mechanism for the application'),
       ('Optimization of Search Algorithms', 2, 'TO_DO', 'MEDIUM', '2023-01-02T09:45:00', '2023-01-02T09:45:00',
        NULL, SELECT id FROM Employee WHERE name = 'Henry',
        SELECT id FROM Sprint WHERE goal = 'Implement Customer Feedback Feature', 'Improve the efficiency of database queries for better performance'),
       ('Mobile App Development for Financial Tracking', 3, 'TO_DO', 'LOW', '2023-01-03T11:30:00', '2023-01-03T11:30:00',
        NULL, SELECT id FROM Employee WHERE name = 'Liam',
        SELECT id FROM Sprint WHERE goal = 'Implement Customer Feedback Feature', 'Create a visually appealing and user-friendly interface'),
       ('Codebase Refactoring for Performance Enhancement', 5, 'RELEASED_TO_PRODUCTION', 'MEDIUM', '2023-02-10T14:00:00', '2023-02-12T18:45:00', '2023-04-01',
           SELECT id FROM Employee WHERE name = 'Peter',
        SELECT id FROM Sprint WHERE goal = 'Bug Fixes and Performance Optimization', 'Integrate data encryption for enhanced security'),
       ('Web Application Security Testing', 8, 'TO_DO', 'HIGH', '2023-01-04T09:15:00', '2023-01-04T09:15:00',
        NULL, SELECT id FROM Employee WHERE name = 'Taylor',
        SELECT id FROM Sprint WHERE goal = 'Prepare Marketing Campaign for Product Launch', 'Address and resolve a bug identified in the user authentication process'),
       ('Implementation of Automated Testing System', 13, 'RELEASED_TO_PRODUCTION', 'MEDIUM', '2023-01-20T10:30:00', '2023-01-25T14:45:00',
        '2023-01-28', SELECT id FROM Employee WHERE name = 'Taylor',
        SELECT id FROM Sprint WHERE goal = 'Enhance User Interface and User Experience', 'Develop components for the application dashboard'),
       ('Development of Cross-platform Mobile App', 1, 'IN_PROGRESS', 'LOW', '2023-05-01T11:00:00', '2023-05-05T16:20:00',
        '2023-05-20', SELECT id FROM Employee WHERE name = 'Xander',
        SELECT id FROM Sprint WHERE goal = 'Implement Security Updates and Bug Fixes', 'Perform a security audit to identify and address potential vulnerabilities'),
       ('Integration with Social Media Platforms', 2, 'IN_PROGRESS', 'MEDIUM', '2023-05-10T13:45:00', '2023-05-12T18:30:00',
        '2023-06-01', SELECT id FROM Employee WHERE name = 'Brian',
        SELECT id FROM Sprint WHERE goal = 'Implement Security Updates and Bug Fixes', 'Add support for multiple languages in the application'),
       ('Administrative Panel Development for Content Management', 5, 'IN_PROGRESS', 'MEDIUM', '2023-06-05T09:30:00', '2023-06-07T14:15:00', '2023-06-20',
           SELECT id FROM Employee WHERE name = 'Ella',
        SELECT id FROM Sprint WHERE goal = 'Implement Security Updates and Bug Fixes', 'Improve performance by optimizing database queries'),
        ('Integration with Third-Party API for Data Synchronization', 8, 'RELEASED_TO_PRODUCTION', 'HIGH', '2023-03-15T10:45:00', '2023-03-20T16:00:00',
        '2023-04-05', SELECT id FROM Employee WHERE name = 'Gabriella',
        SELECT id FROM Sprint WHERE goal = 'Develop New Features for Product Enhancement', 'Create designs for enhancing the user interface'),
       ('Enhancing User Experience through UI/UX Refinement', 13, 'RELEASED_TO_PRODUCTION', 'MEDIUM', '2023-04-01T11:15:00', '2023-04-05T15:30:00',
        '2023-05-20', SELECT id FROM Employee WHERE name = 'Leo',
        SELECT id FROM Sprint WHERE goal = 'Develop New Features for Product Enhancement', 'Conduct load testing to assess application performance under heavy traffic'),
       ('Implementation of Real-time Chat Feature', 5, 'IN_PROGRESS', 'LOW', '2023-06-10T12:30:00', '2023-06-12T17:45:00',
        '2023-08-01', SELECT id FROM Employee WHERE name = 'Owen',
        SELECT id FROM Sprint WHERE goal = 'Implement Performance Improvements', 'Add functionality for collecting and processing user feedback'),
       ('Database Schema Optimization for Scalability', 1, 'IN_PROGRESS', 'MEDIUM', '2023-06-20T09:00:00', '2023-07-03T14:30:00',
        '2023-08-15', SELECT id FROM Employee WHERE name = 'Quentin',
        SELECT id FROM Sprint WHERE goal = 'Implement Performance Improvements', 'Address and fix identified security vulnerabilities'),
       ('Implementation of Multi-factor Authentication', 2, 'IN_PROGRESS', 'HIGH', '2023-06-10T10:30:00', '2023-06-15T15:45:00',
        '2023-08-30', SELECT id FROM Employee WHERE name = 'Quentin',
        SELECT id FROM Sprint WHERE goal = 'Implement Performance Improvements', 'Integrate external API for enhanced functionality'),
        ('Design and Development of User Dashboard', 5, 'TO_DO', 'LOW', '2023-01-01T11:00:00',
         '2023-01-01T11:00:00', NULL, SELECT id FROM Employee WHERE name = 'Quentin',
        SELECT id FROM Sprint WHERE goal = 'Enhance Database Schema and Optimization', 'Create comprehensive documentation for the upcoming release'),
       ('Integration of Machine Learning Algorithms', 13, 'TO_DO', 'MEDIUM', '2023-01-04T12:15:00', '2023-01-04T12:15:00',
        NULL, SELECT id FROM Employee WHERE name = 'Sophia',
        SELECT id FROM Sprint WHERE goal = 'Enhance Database Schema and Optimization', 'Add a dark mode option for the user interface'),
       ('Migration to Cloud Infrastructure', 8, 'TO_DO', 'HIGH', '2023-01-03T09:30:00', '2023-01-03T09:30:00', NULL,
        SELECT id FROM Employee WHERE name = 'Abigail',
        SELECT id FROM Sprint WHERE goal = 'Enhance Database Schema and Optimization', 'Improve efficiency by optimizing database queries'),
       ('Development of Notification System', 5, 'TO_DO', 'MEDIUM', '2023-07-15T10:45:00', '2023-07-15T10:45:00',
        NULL, SELECT id FROM Employee WHERE name = 'Caleb',
        SELECT id FROM Sprint WHERE goal = 'Develop Integration with Third-Party Services', 'Upgrade user authentication system for better security'),
       ('Implementation of Version Control System', 2, 'TO_DO', 'HIGH', '2023-07-25T11:00:00',
        '2023-07-25T11:00:00', NULL, SELECT id FROM Employee WHERE name = 'Elijah',
        SELECT id FROM Sprint WHERE goal = 'Develop Integration with Third-Party Services', 'Integrate real-time notification system for instant updates'),
       ('Performance Monitoring and Analytics Integration', 2, 'TO_DO', 'LOW', '2023-07-01T12:30:00', '2023-07-01T12:30:00', NULL,
           SELECT id FROM Employee WHERE name = 'Theo',
        SELECT id FROM Sprint WHERE goal = 'Develop Integration with Third-Party Services', 'Organize and conduct a training session for end-users');

-- Task label
INSERT INTO Task_label (task_id, label_id)
VALUES (SELECT id FROM Task WHERE task_name = 'Development of Payment Gateway Integration', SELECT id FROM Label WHERE label_name ='Design'),
       (SELECT id FROM Task WHERE task_name = 'Optimization of Search Algorithms', SELECT id FROM Label WHERE label_name ='Design'),
       (SELECT id FROM Task WHERE task_name = 'Mobile App Development for Financial Tracking', SELECT id FROM Label WHERE label_name = 'Design'),
       (SELECT id FROM Task WHERE task_name = 'Codebase Refactoring for Performance Enhancement', SELECT id FROM Label WHERE label_name = 'Debugging'),
       (SELECT id FROM Task WHERE task_name = 'Web Application Security Testing', SELECT id FROM Label WHERE label_name = 'Debugging'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Automated Testing System', SELECT id FROM Label WHERE label_name = 'Debugging'),
       (SELECT id FROM Task WHERE task_name = 'Development of Cross-platform Mobile App', SELECT id FROM Label WHERE label_name = 'Debugging'),
       (SELECT id FROM Task WHERE task_name = 'Integration with Social Media Platforms', SELECT id FROM Label WHERE label_name = 'Creativity'),
       (SELECT id FROM Task WHERE task_name = 'Administrative Panel Development for Content Management', SELECT id FROM Label WHERE label_name = 'Creativity'),
       (SELECT id FROM Task WHERE task_name = 'Integration with Third-Party API for Data Synchronization', SELECT id FROM Label WHERE label_name = 'Creativity'),
       (SELECT id FROM Task WHERE task_name = 'Enhancing User Experience through UI/UX Refinement', SELECT id FROM Label WHERE label_name = 'Creativity'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Real-time Chat Feature', SELECT id FROM Label WHERE label_name = 'Refactoring'),
       (SELECT id FROM Task WHERE task_name = 'Database Schema Optimization for Scalability', SELECT id FROM Label WHERE label_name = 'Refactoring'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Multi-factor Authentication', SELECT id FROM Label WHERE label_name = 'Refactoring'),
       (SELECT id FROM Task WHERE task_name = 'Design and Development of User Dashboard', SELECT id FROM Label WHERE label_name = 'Management'),
       (SELECT id FROM Task WHERE task_name = 'Integration of Machine Learning Algorithms', SELECT id FROM Label WHERE label_name = 'Management'),
       (SELECT id FROM Task WHERE task_name = 'Migration to Cloud Infrastructure', SELECT id FROM Label WHERE label_name = 'Management'),
       (SELECT id FROM Task WHERE task_name = 'Development of Notification System', SELECT id FROM Label WHERE label_name = 'Coding'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Version Control System', SELECT id FROM Label WHERE label_name = 'Coding'),
       (SELECT id FROM Task WHERE task_name = 'Performance Monitoring and Analytics Integration', SELECT id FROM Label WHERE label_name = 'Coding');

-- Task participants
INSERT INTO Task_participants (task_id, employee_id)
VALUES (SELECT id FROM Task WHERE task_name = 'Development of Payment Gateway Integration', SELECT id FROM Employee WHERE name = 'David'),
       (SELECT id FROM Task WHERE task_name = 'Optimization of Search Algorithms', SELECT id FROM Employee WHERE name = 'Henry'),
       (SELECT id FROM Task WHERE task_name = 'Mobile App Development for Financial Tracking', SELECT id FROM Employee WHERE name = 'Liam'),
       (SELECT id FROM Task WHERE task_name = 'Codebase Refactoring for Performance Enhancement', SELECT id FROM Employee WHERE name = 'Peter'),
       (SELECT id FROM Task WHERE task_name = 'Web Application Security Testing', SELECT id FROM Employee WHERE name = 'Taylor'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Automated Testing System', SELECT id FROM Employee WHERE name = 'Taylor'),
       (SELECT id FROM Task WHERE task_name = 'Development of Cross-platform Mobile App', SELECT id FROM Employee WHERE name = 'Xander'),
       (SELECT id FROM Task WHERE task_name = 'Integration with Social Media Platforms', SELECT id FROM Employee WHERE name = 'Brian'),
       (SELECT id FROM Task WHERE task_name = 'Administrative Panel Development for Content Management', SELECT id FROM Employee WHERE name = 'Ella'),
       (SELECT id FROM Task WHERE task_name = 'Integration with Third-Party API for Data Synchronization', SELECT id FROM Employee WHERE name = 'Gabriella'),
       (SELECT id FROM Task WHERE task_name = 'Enhancing User Experience through UI/UX Refinement', SELECT id FROM Employee WHERE name = 'Leo'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Real-time Chat Feature', SELECT id FROM Employee WHERE name = 'Owen'),
       (SELECT id FROM Task WHERE task_name = 'Database Schema Optimization for Scalability', SELECT id FROM Employee WHERE name = 'Quentin'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Multi-factor Authentication', SELECT id FROM Employee WHERE name = 'Quentin'),
       (SELECT id FROM Task WHERE task_name = 'Design and Development of User Dashboard', SELECT id FROM Employee WHERE name = 'Quentin'),
       (SELECT id FROM Task WHERE task_name = 'Integration of Machine Learning Algorithms', SELECT id FROM Employee WHERE name = 'Sophia'),
       (SELECT id FROM Task WHERE task_name = 'Migration to Cloud Infrastructure', SELECT id FROM Employee WHERE name = 'Abigail'),
       (SELECT id FROM Task WHERE task_name = 'Development of Notification System', SELECT id FROM Employee WHERE name = 'Caleb'),
       (SELECT id FROM Task WHERE task_name = 'Implementation of Version Control System', SELECT id FROM Employee WHERE name = 'Elijah'),
       (SELECT id FROM Task WHERE task_name = 'Performance Monitoring and Analytics Integration', SELECT id FROM Employee WHERE name = 'Theo');

-- User project
INSERT INTO User_project (user_id, project_id)
VALUES (SELECT id FROM Employee WHERE name = 'David', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Henry', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Liam', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Peter', SELECT id FROM Project WHERE project_name = 'Marketing Campaign'),
       (SELECT id FROM Employee WHERE name = 'Taylor', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Taylor', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Xander', SELECT id FROM Project WHERE project_name = 'Marketing Campaign'),
       (SELECT id FROM Employee WHERE name = 'Brian', SELECT id FROM Project WHERE project_name = 'Marketing Campaign'),
       (SELECT id FROM Employee WHERE name = 'Ella', SELECT id FROM Project WHERE project_name = 'Marketing Campaign'),
       (SELECT id FROM Employee WHERE name = 'Gabriella', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Leo', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Owen', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Quentin', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Quentin', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Sophia', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Abigail', SELECT id FROM Project WHERE project_name = 'Customer Support Improvement'),
       (SELECT id FROM Employee WHERE name = 'Caleb', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Elijah', SELECT id FROM Project WHERE project_name = 'Software Development'),
       (SELECT id FROM Employee WHERE name = 'Theo', SELECT id FROM Project WHERE project_name = 'Software Development');
